# Pwnagotchi SSH Plugin Configuration Example
# Add these lines to your /etc/pwnagotchi/config.toml file

# SSH Plugin Configuration
main.plugins.ssh.enabled = true

# SSH Server Settings
main.plugins.ssh.port = 22                    # SSH port (default: 22)
main.plugins.ssh.max_connections = 5          # Maximum concurrent connections
main.plugins.ssh.auto_start = true            # Auto-start SSH on boot
main.plugins.ssh.key_auth_only = true         # Only allow SSH key authentication

# Display Settings
main.plugins.ssh.display_on_screen = true     # Show SSH status on display
main.plugins.ssh.ssh_x_coord = 160           # X coordinate for status display
main.plugins.ssh.ssh_y_coord = 80            # Y coordinate for status display

# WebUI Settings
main.plugins.ssh.webui_path = "/ssh"         # WebUI path for SSH management

# Optional: Advanced Settings
# main.plugins.ssh.custom_keys_path = "/opt/pwnagotchi/ssh-keys"  # Custom SSH keys location
# main.plugins.ssh.connection_timeout = 300   # Connection timeout in seconds
# main.plugins.ssh.max_auth_tries = 3         # Maximum authentication attempts
# main.plugins.ssh.display_position = "160,80" # Alternative way to set position

# Example: Restrictive Security Configuration
# main.plugins.ssh.allowed_users = ["pi", "pwnagotchi"]  # Allowed usernames
# main.plugins.ssh.allowed_ips = ["192.168.1.0/24"]      # Allowed IP ranges
# main.plugins.ssh.enable_fail2ban = true                # Enable fail2ban integration

# Example: Development/Testing Configuration
# main.plugins.ssh.debug_mode = true          # Enable debug logging
# main.plugins.ssh.test_mode = false          # Disable actual SSH service control